name: Ontology Documentation CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Create Ontology Documentation 🔧
      run: |
         sudo apt-get update
         sudo apt-get install python3 python3-setuptools python3-pip -y
         sudo apt-get install gcc libpq-dev -y
         sudo apt-get install python-dev-is-python3 python3-pip -y
         sudo apt-get install doxygen graphviz -y
         sudo apt-get install python3-venv python3-wheel -y
         sudo pip3 install wheel pylode==2.13.2 rdflib
         cd docs
         rm index.html
         pylode -i ../owl/ontology.ttl -o index.html
         pylode -i ../examples/cuneiform_a_example.ttl -o cuneiform_a_example.html
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         BRANCH: gh-pages
         FOLDER: docs/
